# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test 

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Install dependencies
      run: go get .

    - name: Running Go linting...
      run: |
        go install golang.org/x/lint/golint@latest
        go lint ./...

    - name: Running Go tests...
      run: go test -tags testing ./...
