name: Log "Deployed" if merge on master

on:
    push:
        branches:
            - main
jobs:
    log-deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Log Deployment
              run: echo "Deployed!"

