name: Test 
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Install dependencies
      run: go mod download

    - name: Running Go linting...
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./...

    - name: Running Go tests...
      run: go test -tags testing ./...

